
export const REDUCER_KEY = 'app';

export const DISPLAY_LOGIN_CATEGORY_SELECTION = `${REDUCER_KEY}/DISPLAY_LOGIN_CATEGORY_SELECTION`;
export const INIT_AUTH_MODAL_IS_OPEN = `${REDUCER_KEY}/INIT_AUTH_MODAL_IS_OPEN`;
export const BURGER_MENU_TOGGLE = `${REDUCER_KEY}/BURGER_MENU_TOGGLE`;
