export const DISPLAY_LOGIN_CATEGORY_SELECTION = 'DISPLAY_LOGIN_CATEGORY_SELECTION';
export const LOGIN_MMODAL_IS_OPEN = 'LOGIN_MMODAL_IS_OPEN';
export const BURGER_MENU_TOGGLE = 'BURGER_MENU_TOGGLE';
