const REDUCER_KEY = 'article';

export const FETCH_PAGINATED = `${REDUCER_KEY}/FETCH_PAGINATED`;
export const SET_PAGINATED = `${REDUCER_KEY}/SET_PAGINATED`;
// export const SET_MAIN_NEWS = `${REDUCER_KEY}/SET_MAIN`;
export const SET_PAGINATED_HAS_MORE = `${REDUCER_KEY}/SET_PAGINATED_HAS_MORE`;
export const ARTICLE_LOADING = `${REDUCER_KEY}/ARTICLE_LOADING`;
export const SET_NEXT_PAGINATION_PAGE = `${REDUCER_KEY}/SET_NEXT_PAGINATION_PAGE`;
export const REFRESH = `${REDUCER_KEY}/REFRESH`;
export const CLEAR = `${REDUCER_KEY}/CLEAR`;
export const FETCH_SINGLE = `${REDUCER_KEY}/FETCH_SINGLE`;
export const SET_SINGLE = `${REDUCER_KEY}/SET_SINGLE`;
export const INCREMENT_CLICK_NUMBER = `${REDUCER_KEY}/INCREMENT_CLICK_NUMBER`;
export const ERROR = `${REDUCER_KEY}/ERROR`;
