export const SM_FETCH_CONTENT = 'SM_FETCH_CONTENT';
export const SM_SET_PAGINATED_CONTENT = 'SM_SET_PAGINATED_CONTENT';
export const SM_SET_PAGINATED_CONTENT_HAS_MORE = 'SM_SET_PAGINATED_CONTENT_HAS_MORE';
export const SM_SET_NEXT_PAGINATION_PAGE = 'SM_SET_NEXT_PAGINATION_PAGE';
export const SM_LOADING_CONTENT = 'SM_LOADING_CONTENT';
export const SM_ERROR = 'SM_ERROR';
