export const GET_USER = 'GET_USER';
export const USER_RECEIVED = 'USER_RECEIVED';
export const ADD_USER_SELECTED_CATEGORIES = 'ADD_USER_SELECTED_CATEGORIES';
export const SET_USER_SELECTED_CATEGORIES = 'SET_USER_SELECTED_CATEGORIES';
export const SET_USER_SELECTED_CATEGORIES_SUCCESS = 'SET_USER_SELECTED_CATEGORIES_SUCCESS';
export const SET_USER_SELECTED_CATEGORIES_ERROR = 'SET_USER_SELECTED_CATEGORIES_ERROR';
