export const REDUCER_KEY = 'auth';

export const GET_USER = `${REDUCER_KEY}/GET_USER`;
export const USER_RECEIVED = `${REDUCER_KEY}/USER_RECEIVED`;
export const ADD_USER_SELECTED_CATEGORIES = `${REDUCER_KEY}/ADD_USER_SELECTED_CATEGORIES`;
export const SET_USER_SELECTED_CATEGORIES = `${REDUCER_KEY}/SET_USER_SELECTED_CATEGORIES`;
export const SET_USER_SELECTED_CATEGORIES_SUCCESS = `${REDUCER_KEY}/SET_USER_SELECTED_CATEGORIES_SUCCESS`;
export const SET_USER_SELECTED_CATEGORIES_ERROR = `${REDUCER_KEY}/SET_USER_SELECTED_CATEGORIES_ERROR`;
